# Generated by Django 3.2.7 on 2021-12-19 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='block', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='unblock', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
