# Generated by Django 3.2.7 on 2021-12-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0002_user_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_follow',
            old_name='user_id',
            new_name='use_id',
        ),
    ]
