# Generated by Django 3.2.9 on 2021-12-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song',
            new_name='songs',
        ),
    ]
