# Generated by Django 3.2.7 on 2021-11-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_like',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post_like',
            old_name='user_id',
            new_name='user',
        ),
    ]
