# Generated by Django 3.2.7 on 2021-10-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='voices',
            old_name='post_id',
            new_name='post',
        ),
    ]
