# Generated by Django 3.2.7 on 2021-10-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211009_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_user',
            old_name='user_id',
            new_name='user',
        ),
    ]
