# Generated by Django 3.2.7 on 2021-11-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reporting',
            field=models.IntegerField(default=False),
        ),
    ]
