# Generated by Django 3.2.9 on 2021-11-24 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211124_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='comment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='account.post_comment'),
        ),
    ]
