# Generated by Django 3.2.7 on 2021-10-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211014_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
